from .test_bank_account_form import BankAccountFormTestCase
from .test_category_form import CategoryFormTestCase
from .test_edit_user_details_form import EditUserDetailsFormTestCase
from .test_log_in_form import LogInFormTestCase
from .test_pot_account_form import PotAccountFormTestCase
from .test_sign_up_form import SignUpFormTestCase
