from .test_get_greggor_logo_tag import GetGreggorTemplateTagTestCase
from .test_target_tag import GetCompletenessTemplateTagTestCase
from .test_get_greggor_type_tag import GetGreggorTypeTemplateTagTestCase
from .test_get_overall_completeness_tag import GetOverallCompletenessTemplateTagTestCase
from .test_get_overall_greggor_type_tag import GetOverallGreggorTypeTemplateTagTestCase
