from .test_get_greggor_logo_tag import GetGreggorTemplateTagTestCase
from .test_target_tag import GetCompletenessTemplateTagTestCase
from .test_maths_template_tags import DivideTemplateTagTestCase, SigFigsTemplateTagTestCase
