# Generated by Django 4.1.3 on 2023-01-19 15:52

from django.db import migrations, models
import financial_companion.models.user_model


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                upload_to=financial_companion.models.user_model.change_filename
            ),
    ]
