# Generated by Django 4.1.3 on 2023-01-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_companion", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
