# Generated by Django 4.1.3 on 2023-01-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0003_account'),
        ('financial_companion', '0003_category'),
    ]

    operations = [
    ]
