# Generated by Django 4.1.3 on 2023-01-21 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0004_merge_0003_account_0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='change_filename')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('gbp', 'Gbp'), ('usd', 'Usd'), ('eur', 'Eur'), ('jpy', 'Jpy'), ('cny', 'Cny'), ('aud', 'Aud'), ('cad', 'Cad'), ('kzt', 'Kzt'), ('inr', 'Inr'), ('rub', 'Rub'), ('nzd', 'Nzd'), ('chf', 'Chf')], max_length=3)),
                ('time_of_transaction', models.DateTimeField(default=datetime.datetime(2023, 1, 21, 18, 32, 18, 231485))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_companion.category')),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_account', to='financial_companion.account')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_account', to='financial_companion.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
