# Generated by Django 4.1.3 on 2023-01-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0004_potaccount'),
        ('financial_companion', '0005_usertarget'),
    ]

    operations = [
    ]
