# Generated by Django 4.1.3 on 2023-01-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0006_merge_0004_potaccount_0005_usertarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytarget',
            name='currency',
            field=models.CharField(
                choices=[
                    ('gbp',
                     'Gbp'),
                    ('usd',
                     'Usd'),
                    ('eur',
                     'Eur'),
                    ('jpy',
                     'Jpy'),
                    ('cny',
                     'Cny'),
                    ('aud',
                     'Aud'),
                    ('cad',
                     'Cad'),
                    ('kzt',
                     'Kzt'),
                    ('inr',
                     'Inr'),
                    ('rub',
                     'Rub'),
                    ('nzd',
                     'Nzd'),
                    ('chf',
                     'Chf')],
                default='gbp',
                max_length=5),
        ),
        migrations.AlterField(
            model_name='usertarget',
            name='currency',
            field=models.CharField(
                choices=[
                    ('gbp',
                     'Gbp'),
                    ('usd',
                     'Usd'),
                    ('eur',
                     'Eur'),
                    ('jpy',
                     'Jpy'),
                    ('cny',
                     'Cny'),
                    ('aud',
                     'Aud'),
                    ('cad',
                     'Cad'),
                    ('kzt',
                     'Kzt'),
                    ('inr',
                     'Inr'),
                    ('rub',
                     'Rub'),
                    ('nzd',
                     'Nzd'),
                    ('chf',
                     'Chf')],
                default='gbp',
                max_length=5),
        ),
    ]
