# Generated by Django 4.1.3 on 2023-01-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0005_transaction'),
        ('financial_companion', '0007_alter_categorytarget_currency_and_more'),
    ]

    operations = [
    ]
