# Generated by Django 4.1.3 on 2023-01-21 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0008_merge_20230121_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    1,
                    21,
                    19,
                    53,
                    1,
                    628819,
                    tzinfo=datetime.timezone.utc)),
        ),
    ]
