# Generated by Django 4.1.3 on 2023-01-21 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0009_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    1,
                    21,
                    20,
                    5,
                    3,
                    642782,
                    tzinfo=datetime.timezone.utc)),
        ),
    ]
