# Generated by Django 4.1.3 on 2023-01-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0010_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
