# Generated by Django 4.1.3 on 2023-01-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0011_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7)),
                ('timespan', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('gbp', 'Gbp'), ('usd', 'Usd'), ('eur', 'Eur'), ('jpy', 'Jpy'), ('cny', 'Cny'), ('aud', 'Aud'), ('cad', 'Cad'), ('kzt', 'Kzt'), ('inr', 'Inr'), ('rub', 'Rub'), ('nzd', 'Nzd'), ('chf', 'Chf')], default='gbp', max_length=5)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_companion.potaccount')),
            ],
            options={
                'unique_together': {('transaction_type', 'timespan', 'account_id')},
            },
        ),
    ]
