# Generated by Django 4.1.3 on 2023-01-23 14:13

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields
import financial_companion.models.accounts_model


class Migration(migrations.Migration):

    dependencies = [
        ("financial_companion", "0011_alter_transaction_time_of_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "potaccount_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="financial_companion.potaccount",
                    ),
                ),
                ("bank_name", models.CharField(max_length=50)),
                (
                    "account_number",
                    encrypted_fields.fields.EncryptedCharField(
                        max_length=8,
                        validators=[financial_companion.models.accounts_model.only_int],
                    ),
                ),
                (
                    "sort_code",
                    encrypted_fields.fields.EncryptedCharField(
                        max_length=6,
                        validators=[financial_companion.models.accounts_model.only_int],
                    ),
                ),
                (
                    "iban",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=34
                    ),
                ),
            ],
            bases=("financial_companion.potaccount",),
        ),
    ]
