# Generated by Django 4.1.3 on 2023-01-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_companion", "0012_accounttarget"),
        ("financial_companion", "0012_bankaccount"),
    ]

    operations = []
