# Generated by Django 4.1.3 on 2023-01-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0013_bankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-time_of_transaction']},
        ),
    ]
