# Generated by Django 4.1.3 on 2023-01-23 18:59

import django.core.validators
from django.db import migrations, models
import encrypted_fields.fields
import financial_companion.models.accounts_model


class Migration(migrations.Migration):

    dependencies = [
        ("financial_companion", "0013_merge_0012_accounttarget_0012_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=encrypted_fields.fields.EncryptedCharField(
                max_length=8,
                validators=[
                    financial_companion.models.accounts_model.only_int,
                    django.core.validators.MinLengthValidator(
                        8, "Account number must be 8 digits long"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="iban",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                max_length=33,
                validators=[
                    django.core.validators.MinLengthValidator(
                        15, "Iban must be a minimum of 15 characters long"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="sort_code",
            field=encrypted_fields.fields.EncryptedCharField(
                max_length=6,
                validators=[
                    financial_companion.models.accounts_model.only_int,
                    django.core.validators.MinLengthValidator(
                        6, "Sort code must be 6 digits long"
                    ),
                ],
            ),
        ),
    ]
