# Generated by Django 4.1.3 on 2023-01-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_companion", "0013_bankaccount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="potaccount", old_name="user_id", new_name="user",
        ),
        migrations.RenameField(
            model_name="usertarget", old_name="user_id", new_name="user",
        ),
    ]
