# Generated by Django 4.1.3 on 2023-01-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_companion", "0014_alter_transaction_options"),
        ("financial_companion", "0014_rename_user_id_potaccount_user_and_more"),
    ]

    operations = []
