# Generated by Django 4.1.3 on 2023-01-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_companion", "0015_merge_20230126_1859"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accounttarget", old_name="account_id", new_name="account",
        ),
        migrations.RenameField(
            model_name="categorytarget", old_name="category_id", new_name="category",
        ),
        migrations.AlterUniqueTogether(
            name="accounttarget",
            unique_together={("transaction_type", "timespan", "account")},
        ),
        migrations.AlterUniqueTogether(
            name="categorytarget",
            unique_together={("transaction_type", "timespan", "category")},
        ),
    ]
