# Generated by Django 4.1.3 on 2023-01-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "financial_companion",
            "0016_rename_account_id_accounttarget_account_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receiver_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reciever%(app_label)s_%(class)s_related",
                to="financial_companion.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_account%(app_label)s_%(class)s_related",
                to="financial_companion.account",
            ),
        ),
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="change_filename")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("gbp", "Gbp"),
                            ("usd", "Usd"),
                            ("eur", "Eur"),
                            ("jpy", "Jpy"),
                            ("cny", "Cny"),
                            ("aud", "Aud"),
                            ("cad", "Cad"),
                            ("kzt", "Kzt"),
                            ("inr", "Inr"),
                            ("rub", "Rub"),
                            ("nzd", "Nzd"),
                            ("chf", "Chf"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=5,
                    ),
                ),
                ("end_date", models.DateField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_companion.category",
                    ),
                ),
                (
                    "receiver_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reciever%(app_label)s_%(class)s_related",
                        to="financial_companion.account",
                    ),
                ),
                (
                    "sender_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_account%(app_label)s_%(class)s_related",
                        to="financial_companion.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("sender_account", "receiver_account")},
            },
        ),
    ]
