# Generated by Django 4.1.3 on 2023-02-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0017_alter_transaction_receiver_account_and_more'),
        ('financial_companion', '0018_alter_transaction_category'),
    ]

    operations = [
    ]
