# Generated by Django 4.1.3 on 2023-02-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0018_alter_recurringtransaction_options_and_more'),
        ('financial_companion', '0020_alter_recurringtransaction_options_and_more'),
    ]

    operations = [
    ]
