# Generated by Django 4.1.3 on 2023-02-10 15:18

from django.db import migrations, models
import financial_companion.models.user_group_model


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0021_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_picture',
            field=models.ImageField(blank=True, upload_to=financial_companion.models.user_group_model.change_filename),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='invite_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
