# Generated by Django 4.1.3 on 2023-02-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0021_merge_20230210_1406'),
        ('financial_companion', '0022_usergroup_group_picture_alter_usergroup_invite_code'),
    ]

    operations = [
    ]
