# Generated by Django 4.1.3 on 2023-02-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0023_quizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeded', models.BooleanField()),
                ('questions', models.ManyToManyField(to='financial_companion.quizquestion')),
            ],
        ),
    ]
