# Generated by Django 4.1.3 on 2023-02-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0023_merge_20230212_1250'),
        ('financial_companion', '0024_quizscore'),
    ]

    operations = [
    ]
