# Generated by Django 4.1.3 on 2023-03-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0026_alter_recurringtransaction_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
