# Generated by Django 4.1.3 on 2023-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0026_alter_recurringtransaction_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='transactions',
            field=models.ManyToManyField(to='financial_companion.transaction'),
        ),
        migrations.DeleteModel(
            name='LinkRecurringTransaction',
        ),
    ]
