# Generated by Django 4.1.3 on 2023-03-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0027_alter_accounttarget_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttarget',
            old_name='transaction_type',
            new_name='target_type',
        ),
        migrations.RenameField(
            model_name='categorytarget',
            old_name='transaction_type',
            new_name='target_type',
        ),
        migrations.RenameField(
            model_name='usertarget',
            old_name='transaction_type',
            new_name='target_type',
        ),
        migrations.AlterUniqueTogether(
            name='accounttarget',
            unique_together={('target_type', 'timespan', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytarget',
            unique_together={('target_type', 'timespan', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='usertarget',
            unique_together={('target_type', 'timespan', 'user')},
        ),
    ]
