# Generated by Django 4.1.3 on 2023-03-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0027_recurringtransaction_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='start_date',
            field=models.DateField(),
        ),
    ]
