# Generated by Django 4.1.3 on 2023-03-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0027_alter_accounttarget_amount_and_more'),
        ('financial_companion', '0027_remove_potaccount_user_account_user'),
    ]

    operations = [
    ]
