# Generated by Django 4.1.3 on 2023-03-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0028_merge_20230309_1705'),
        ('financial_companion', '0028_rename_transaction_type_accounttarget_target_type_and_more'),
    ]

    operations = [
    ]
