# Generated by Django 4.1.3 on 2023-03-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0029_merge_20230309_2026'),
        ('financial_companion', '0030_merge_20230309_2009'),
    ]

    operations = [
    ]
