# Generated by Django 4.1.3 on 2023-03-09 22:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0031_merge_20230309_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, max_digits=15, validators=[
                    django.core.validators.MinValueValidator(
                        Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, max_digits=15, validators=[
                    django.core.validators.MinValueValidator(
                        Decimal('0.01'))]),
        ),
    ]
