# Generated by Django 4.1.3 on 2023-03-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0028_alter_recurringtransaction_start_date'),
        ('financial_companion', '0031_merge_20230309_2050'),
    ]

    operations = [
    ]
