# Generated by Django 4.1.3 on 2023-03-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_companion', '0032_alter_recurringtransaction_amount_and_more'),
        ('financial_companion', '0032_merge_20230310_1816'),
    ]

    operations = [
    ]
